### ISSUE TITLE
Collector fails because it may create modifications to repository files

### ISSUE THREAD

**Issue by gjdev** [dependencies-io/collector-js-lerna#18]
The collector checks (and throws an error) when the `lerna bootstrap` or `npm install` commands modify repository files. See https://github.com/dependencies-io/collector-js-lerna/blob/master/entrypoint.js#L43.

However, since running `npm install` with a different npm version than what a developer has used when creating a package-lock.josn file, may actually alter the package-lock.json, there is a pretty high change that the collector will fail. E.g. npm may change the ordering of entries in package-lock.json when doing an install with npm 5.3.0 and later running npm install with 5.5.1 (the version the collector seems to use currently).

**Comment by davegaeddert** [comment]
Thanks @gjdev, that's a great point. Thoughts on what to do here? The original intent was to try and help people catch when their lockfile is out-of-date or out-of-sync for some other reason. That way when we send PRs, they don't also include some unrelated changes to the lockfile (other than what we were trying to update).

**Comment by gjdev** [comment]
Maybe make the check optional? It' s actually a bit strange that npm behaves like this, might be a bug with npm. This may stabilize with future npm versions.

**Comment by davegaeddert** [comment]
The new js component for dependencies.io v2 can be found here: https://github.com/dependencies-io/js

A lot has changed, and this is probably not an issue anymore.
