### ISSUE TITLE
Allow specifying node/npm version

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/collector-js-lerna#19]
I need to run lerna collector with npm `v5.6.0` or higher because otherwise `package-lock.json` files are generated differently depending on OS when there are `optionalDependencies` present
https://github.com/npm/npm/issues/17722#issuecomment-347531151

**Comment by davegaeddert** [comment]
Ok it should be using 5.6.0 now: https://github.com/dependencies-io/collector-js-lerna/commit/bdc69396e68e05e256bbc4c4c24111032f955efb#diff-8ee2343978836a779dc9f8d6b794c3b2R1932

I did the same for the actor. I've been expecting that at some point we might have to add a way to specify the node/npm version exactly -- just been waiting to see if it would actually be an issue. Feels like it still wouldn't have been one if we had been using the latest available version (which we should have been).

I'm going to close this for now. Happy to reopen if it need be!
