### ISSUE TITLE
Collector fails for yarn 1.5.1 / node 9.1

### ISSUE THREAD

**Issue by pcardune** [dependencies-io/collector-js-lerna#36]
I have the following in my top-level package.json file:

```json
  "engines": {
    "node": "9.1.0",
    "yarn": "1.5.1"
  },
```

This is producing the following error:

```
yarn install v1.3.2
[1/5] Validating package.json...
error @: The engine "node" is incompatible with this module. Expected version "9.1.0".
error @: The engine "yarn" is incompatible with this module. Expected version "1.5.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/usr/src/collector/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/usr/src/collector/node_modules/shelljs/src/common.js:110:27)
    at Object._exec (/usr/src/collector/node_modules/shelljs/src/exec.js:206:12)
    at Object.exec (/usr/src/collector/node_modules/shelljs/src/common.js:335:23)
    at Object.<anonymous> (/usr/src/collector/entrypoint.js:19:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

Is there a workaround? I might be able to remove the yarn 1.5.1 constraint, but I need the node constraint for other services that use the `package.json` config to do fancy things.

**Comment by davegaeddert** [comment]
Hey @pcardune, we're actually getting really close to launching a big update to dependencies.io (hopefully tomorrow). Since you're just getting started, do you mind if I point you to that instead? I think it will handle a lot of these things better than this repo does.

You can get there now by hovering over a hidden "v2" link in the sidebar:
![image](https://user-images.githubusercontent.com/649496/37855904-b1449a56-2ebf-11e8-9d61-994fba13e6dc.png)

Not sure what your repo looks like exactly, but if you switch over to v2 then the config is slightly different. If you're using yarn workspaces then you only need to point it to the root of your repo. Something like this:
```yml
version: 2
dependencies:
- type: js
  path: /
```

New repo is here: https://github.com/dependencies-io/js

Thanks for your patience! Let me know if you have any questions. Feel free to use the chat on the site if you want to talk specifics about private info.

**Comment by davegaeddert** [comment]
Hey @pcardune, looks like things may not have worked like you hoped? If you have any feedback, I'd love to hear it. We're just getting started with these new v2 changes and if there are things that didn't work or didn't work how you expected, we'd like to fix it. Thanks for giving it a try!

**Comment by pcardune** [comment]
My repository layout is perhaps a bit unusual. I'm using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) and [lerna](https://github.com/lerna/lerna) to manage multiple packages in a monorepo. These packages include both pure libraries and applications. The applications include both front-end apps that get bundled by webpack, and vanilla node.js apps.

The packages share many of the same dependencies. When they do have common dependencies, we make sure the dependencies are all exactly the same version to avoid confusion and bugs.

With the new dependencies.io, a separate pull request is submitted for each package in the repo. What I'd like to get instead is a single pull request that upgrades a particular dependency for every package in the repo. Otherwise our builds fail due to dependency version mismatches. The issue could be caused by how our dependencies are listed in various packages (peerDependencies vs optionalDependencies, etc), but nevertheless I'd like the option to keep all common dependencies in lock step with each other.

Is that possible?

**Comment by davegaeddert** [comment]
Thanks for the response.

We left out the idea of grouping/batching updates in this first implementation of the new config, but it's something we plan to work back in. While your situation is a little bit unusual, I think it makes plenty of sense. The other (probably more common) use case that we were planning to deal with is being able to group several dependencies into 1 PR for the *same* package.json. Particularly for scoped packages or things like React, where you usually want to update "react" and "react-dom" together.

So I think what we'll do is take a look at our last idea for tackling that and check that it will work for your use case too. 

Might just be an addition to [filters](https://www.dependencies.io/docs/dependencies-yml/filtering-updates/) that looks something like this?
```yml
version: 2
dependencies:
- type: js
  path: /
  manifest_updates:
    filters:
    - name: "react.*"
      versions: Y.Y.Y
      update_together: true
    - name: ".*"
      versions: Y.Y.Y
```
